# Generated by Django 4.1.2 on 2022-10-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cpuGen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuGen', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='cpuType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='diskCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskCap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='diskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diskType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ekran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekran', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelAdi', models.CharField(max_length=20)),
                ('modelNo', models.CharField(max_length=20)),
                ('resim', models.CharField(max_length=20)),
                ('cpuGen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.cpugen')),
                ('cpuType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.cputype')),
                ('diskCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.diskcap')),
                ('diskType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.disktype')),
                ('ekran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.ekran')),
            ],
        ),
        migrations.CreateModel(
            name='laptopFromSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiyat', models.FloatField()),
                ('puan', models.FloatField()),
                ('URL', models.URLField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.laptop')),
            ],
        ),
        migrations.CreateModel(
            name='marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='oSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oSystem', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteAdi', models.CharField(max_length=20)),
                ('logo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='laptopInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.laptop')),
                ('laptopSiteOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.laptopfromsite')),
            ],
        ),
        migrations.AddField(
            model_name='laptopfromsite',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.site'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='marka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.marka'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.osystem'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='ram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productListPage.ram'),
        ),
    ]
