# Generated by Django 4.1.2 on 2022-10-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productListPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marka',
            old_name='marka',
            new_name='markaAdi',
        ),
    ]
