# Generated by Django 4.1.2 on 2022-10-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productListPage', '0002_rename_marka_marka_markaadi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptopinstance',
            name='laptopSiteOne',
        ),
        migrations.AddField(
            model_name='laptopinstance',
            name='laptopDeals',
            field=models.ManyToManyField(to='productListPage.laptopfromsite'),
        ),
    ]
